//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip
    {
        public int id { get; set; }
        public string un { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public string data { get; set; }
    }
}
